    server.port=8080
    spring.application.name=GATEWAY

    ############################
     # EUREKA
    ############################
    eureka.client.service-url.defaultZone=http://localhost:8761/eureka
    eureka.client.register-with-eureka=true
    eureka.client.fetch-registry=true
    # Prevent duplicate CORS headers when downstream services also set them
    spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

    ############################
    # ROUTES
    ############################

    # USER-AUTH-SERVICE (auth, users, instructor requests, CV analysis, test AI)
    spring.cloud.gateway.routes[0].id=user-auth
    spring.cloud.gateway.routes[0].uri=lb://USER-AUTH-SERVICE
    spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/user/**,/api/instructor-request/**,/api/cv/**,/api/test/**


    # NOTIFICATION-SERVICE (PostController @RequestMapping("/posts"))
    spring.cloud.gateway.routes[1].id=notification-service
    spring.cloud.gateway.routes[1].uri=lb://NOTIFICATION-SERVICE
    spring.cloud.gateway.routes[1].predicates[0]=Path=/notifications/**
    ############################
    # CORS
    ############################

    spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
    spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
    spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
    spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true
#################################################
# SWAGGER
#################################################

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=USER-AUTH-SERVICE
springdoc.swagger-ui.urls[0].url=/v3/api-docs/user-service

spring.cloud.gateway.routes[2].id=user-service-docs
spring.cloud.gateway.routes[2].uri=lb://USER-AUTH-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/v3/api-docs/user-service
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/v3/api-docs/user-service,/v3/api-docs